//! Bounded binary framing for Sealr's future supervisor-worker boundary.
//!
//! Capabilities are transferred out of band. The start frame only names their
//! slots and roles; the result frame is forbidden from carrying capabilities.
//! Every length and count is checked against a wire limit before allocation.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use std::error::Error;
use std::fmt;

/// Version accepted and emitted by this codec.
pub const PROTOCOL_VERSION: u16 = 1;
/// Eight-byte identity at the beginning of every frame.
pub const FRAME_MAGIC: [u8; 8] = *b"SEALRIPC";
/// Bytes in the common frame header.
pub const FRAME_HEADER_BYTES: usize = 16;
/// Bytes in the fixed version 1 start payload.
pub const START_PAYLOAD_BYTES: usize = 196;
/// Bytes in a complete version 1 start frame.
pub const START_FRAME_BYTES: usize = FRAME_HEADER_BYTES + START_PAYLOAD_BYTES;
/// Bytes before variable manifest and finding records in a result payload.
pub const RESULT_FIXED_PAYLOAD_BYTES: usize = 124;
/// Largest complete frame accepted or emitted by the codec.
pub const MAX_FRAME_BYTES: usize = 4 * 1024 * 1024;
/// Largest capability count accepted in a start request.
pub const MAX_CAPABILITIES: u16 = 2;
/// Largest manifest member count accepted in a result.
pub const MAX_MANIFEST_MEMBERS: u32 = 10_000;
/// Largest finding count accepted in a result.
pub const MAX_FINDINGS: u32 = 10_000;
/// Largest UTF-8 byte length of a protocol path.
pub const MAX_PATH_BYTES: usize = 4 * 1024;
/// Largest byte length of a finding code.
pub const MAX_FINDING_CODE_BYTES: usize = 128;
/// Largest UTF-8 byte length of finding detail.
pub const MAX_FINDING_DETAIL_BYTES: usize = 1024;

const FRAME_KIND_START: u8 = 1;
const FRAME_KIND_RESULT: u8 = 2;
const NO_CAPABILITY_SLOT: u16 = u16::MAX;
const MANIFEST_ENTRY_FIXED_BYTES: usize = 44;
const FINDING_FIXED_BYTES: usize = 8;

/// Effect selected for a worker invocation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ExecutionMode {
    /// Interpret and verify without writing a stage.
    Inspect,
    /// Interpret, verify, and write through a stage capability.
    Materialize,
}

/// Exact archive interpretation contract selected by the supervisor.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InterpretationProfile {
    /// Compatibility strict ASCII ZIP32 profile.
    StrictAsciiV1,
    /// Closed strict ASCII ZIP32 profile.
    StrictAsciiV2,
}

/// Resource limits bound to one worker invocation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ResourceLimits {
    /// Maximum complete source length.
    pub max_archive_bytes: u64,
    /// Maximum member count.
    pub max_files: u64,
    /// Maximum expanded bytes for one member.
    pub max_member_bytes: u64,
    /// Maximum total expanded bytes.
    pub max_total_bytes: u64,
    /// Optional maximum expansion ratio.
    pub max_ratio: Option<u64>,
    /// Maximum canonical path depth.
    pub max_path_depth: u32,
    /// Maximum archive metadata bytes.
    pub max_metadata_bytes: u64,
}

/// Bounded operation description sent from supervisor to worker.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StartRequest {
    /// Nonzero correlation identifier generated by the supervisor.
    pub operation_id: [u8; 16],
    /// Requested worker effect.
    pub mode: ExecutionMode,
    /// Selected interpretation contract.
    pub interpretation_profile: InterpretationProfile,
    /// Whether completed member files require a sync operation.
    pub member_sync: bool,
    /// Number of capabilities received out of band with the frame.
    pub capability_count: u16,
    /// Slot containing the immutable read-only source capability.
    pub source_capability: u16,
    /// Optional slot containing the stage directory capability.
    pub stage_capability: Option<u16>,
    /// Exact byte length of the immutable source.
    pub source_len: u64,
    /// SHA-256 of the complete immutable source.
    pub source_sha256: [u8; 32],
    /// SHA-256 identity of the selected interpretation profile.
    pub interpretation_profile_sha256: [u8; 32],
    /// SHA-256 identity of the compiled policy.
    pub policy_sha256: [u8; 32],
    /// Resource limits for the invocation.
    pub limits: ResourceLimits,
}

/// Terminal state reported by the worker.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WorkerStatus {
    /// Interpretation and required verification completed.
    Complete,
    /// The archive was coherently rejected.
    Rejected,
    /// Execution failed without a complete semantic result.
    Failed,
}

/// Kind of object claimed by a result manifest entry.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ManifestKind {
    /// Regular file with measured size and content digest.
    File,
    /// Directory with zero size and zero digest.
    Directory,
}

/// One canonical object claimed by a complete worker result.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ManifestEntry {
    /// Canonical relative slash-separated path.
    pub path: String,
    /// Object kind.
    pub kind: ManifestKind,
    /// Measured file size, or zero for a directory.
    pub size: u64,
    /// File content SHA-256, or zero bytes for a directory.
    pub sha256: [u8; 32],
}

/// Severity of a protocol finding.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FindingSeverity {
    /// Non-fatal diagnostic.
    Warning,
    /// Error that prevents a complete result.
    Error,
}

/// Bounded diagnostic claimed by a worker.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProtocolFinding {
    /// Finding severity.
    pub severity: FindingSeverity,
    /// Stable lowercase machine code.
    pub code: String,
    /// Bounded human-readable detail.
    pub detail: String,
    /// Optional canonical member path.
    pub member_path: Option<String>,
}

/// Bounded, correlated result returned by a worker.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WorkerResult {
    /// Operation ID copied from the accepted start request.
    pub operation_id: [u8; 16],
    /// Terminal worker state.
    pub status: WorkerStatus,
    /// Worker-observed interpretation profile identity.
    pub interpretation_profile_sha256: [u8; 32],
    /// Optional layout identity available after coherent interpretation.
    pub layout_root: Option<[u8; 32]>,
    /// Content identity available only for complete verification.
    pub content_root: Option<[u8; 32]>,
    /// Entries must be strictly ordered by canonical path.
    pub manifest: Vec<ManifestEntry>,
    /// Bounded diagnostics emitted by the worker.
    pub findings: Vec<ProtocolFinding>,
}

/// Stable category of a protocol rejection.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProtocolErrorKind {
    /// Complete input exceeds the frame limit.
    FrameTooLarge,
    /// A required field or declared payload is incomplete.
    Truncated,
    /// Bytes remain after the declared frame or payload content.
    TrailingBytes,
    /// Frame magic does not identify this protocol.
    InvalidMagic,
    /// Frame version is not supported.
    UnsupportedVersion,
    /// Frame kind does not match the selected decoder.
    UnexpectedFrameKind,
    /// A reserved byte or field is nonzero.
    ReservedNonZero,
    /// A declared length or count exceeds its protocol limit.
    LimitExceeded,
    /// Declared counts cannot fit in the available bytes.
    CountInconsistent,
    /// An enum or Boolean field has an unknown value.
    InvalidEnum,
    /// Declared capability slots do not match transport authority.
    CapabilityMismatch,
    /// A result operation ID does not match the expected invocation.
    CorrelationMismatch,
    /// A wire string is not valid UTF-8.
    InvalidUtf8,
    /// A wire string is outside its canonical language.
    InvalidString,
    /// Individually valid fields form an incoherent state.
    InvalidSemanticState,
    /// Manifest paths are duplicated or not strictly ordered.
    NonCanonicalOrder,
    /// Checked length arithmetic overflowed.
    IntegerOverflow,
    /// A bounded, fallible allocation failed.
    AllocationFailed,
}

/// Non-allocating protocol error with a byte location and static detail.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ProtocolError {
    /// Stable error category.
    pub kind: ProtocolErrorKind,
    /// Absolute byte offset at or after the rejected field.
    pub offset: usize,
    /// Static diagnostic detail that never includes hostile input.
    pub detail: &'static str,
}

impl ProtocolError {
    const fn new(kind: ProtocolErrorKind, offset: usize, detail: &'static str) -> Self {
        Self {
            kind,
            offset,
            detail,
        }
    }
}

impl fmt::Display for ProtocolError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "protocol error at byte {}: {}",
            self.offset, self.detail
        )
    }
}

impl Error for ProtocolError {}

/// Encodes a validated version 1 start request.
pub fn encode_start(request: &StartRequest) -> Result<Vec<u8>, ProtocolError> {
    validate_start(request, request.capability_count)?;
    let mut output = allocate_frame(START_FRAME_BYTES)?;
    encode_header(&mut output, FRAME_KIND_START, START_PAYLOAD_BYTES)?;
    output.extend_from_slice(&request.operation_id);
    output.push(match request.mode {
        ExecutionMode::Inspect => 0,
        ExecutionMode::Materialize => 1,
    });
    output.push(match request.interpretation_profile {
        InterpretationProfile::StrictAsciiV1 => 1,
        InterpretationProfile::StrictAsciiV2 => 2,
    });
    output.push(u8::from(request.member_sync));
    output.push(0);
    push_u16(&mut output, request.capability_count);
    push_u16(&mut output, request.source_capability);
    push_u16(
        &mut output,
        request.stage_capability.unwrap_or(NO_CAPABILITY_SLOT),
    );
    push_u16(&mut output, 0);
    push_u64(&mut output, request.source_len);
    output.extend_from_slice(&request.source_sha256);
    output.extend_from_slice(&request.interpretation_profile_sha256);
    output.extend_from_slice(&request.policy_sha256);
    push_u64(&mut output, request.limits.max_archive_bytes);
    push_u64(&mut output, request.limits.max_files);
    push_u64(&mut output, request.limits.max_member_bytes);
    push_u64(&mut output, request.limits.max_total_bytes);
    output.push(u8::from(request.limits.max_ratio.is_some()));
    output.extend_from_slice(&[0; 7]);
    push_u64(&mut output, request.limits.max_ratio.unwrap_or(0));
    push_u32(&mut output, request.limits.max_path_depth);
    push_u32(&mut output, 0);
    push_u64(&mut output, request.limits.max_metadata_bytes);
    debug_assert_eq!(output.len(), START_FRAME_BYTES);
    Ok(output)
}

/// Decodes a complete start frame and validates its out-of-band capability count.
pub fn decode_start(
    input: &[u8],
    received_capabilities: u16,
) -> Result<StartRequest, ProtocolError> {
    let payload = decode_header(input, FRAME_KIND_START)?;
    if payload.len() != START_PAYLOAD_BYTES {
        return Err(ProtocolError::new(
            ProtocolErrorKind::CountInconsistent,
            FRAME_HEADER_BYTES,
            "start payload has the wrong fixed length",
        ));
    }
    let mut cursor = Cursor::new(payload, FRAME_HEADER_BYTES);
    let operation_id = cursor.array()?;
    let mode = match cursor.u8()? {
        0 => ExecutionMode::Inspect,
        1 => ExecutionMode::Materialize,
        _ => return Err(cursor.error(ProtocolErrorKind::InvalidEnum, "unknown execution mode")),
    };
    let interpretation_profile = match cursor.u8()? {
        1 => InterpretationProfile::StrictAsciiV1,
        2 => InterpretationProfile::StrictAsciiV2,
        _ => {
            return Err(cursor.error(
                ProtocolErrorKind::InvalidEnum,
                "unknown interpretation profile",
            ));
        }
    };
    let member_sync = decode_bool(cursor.u8()?, &cursor, "invalid member-sync flag")?;
    require_zero(cursor.u8()?, &cursor, "start reserved byte is nonzero")?;
    let capability_count = cursor.u16()?;
    let source_capability = cursor.u16()?;
    let encoded_stage_capability = cursor.u16()?;
    let stage_capability =
        (encoded_stage_capability != NO_CAPABILITY_SLOT).then_some(encoded_stage_capability);
    require_zero(cursor.u16()?, &cursor, "start reserved field is nonzero")?;
    let source_len = cursor.u64()?;
    let source_sha256 = cursor.array()?;
    let interpretation_profile_sha256 = cursor.array()?;
    let policy_sha256 = cursor.array()?;
    let max_archive_bytes = cursor.u64()?;
    let max_files = cursor.u64()?;
    let max_member_bytes = cursor.u64()?;
    let max_total_bytes = cursor.u64()?;
    let max_ratio_present = decode_bool(cursor.u8()?, &cursor, "invalid max-ratio presence flag")?;
    cursor.zeroes(7, "max-ratio reserved bytes are nonzero")?;
    let max_ratio_value = cursor.u64()?;
    let max_path_depth = cursor.u32()?;
    require_zero(cursor.u32()?, &cursor, "limits reserved field is nonzero")?;
    let max_metadata_bytes = cursor.u64()?;
    cursor.finish()?;

    let request = StartRequest {
        operation_id,
        mode,
        interpretation_profile,
        member_sync,
        capability_count,
        source_capability,
        stage_capability,
        source_len,
        source_sha256,
        interpretation_profile_sha256,
        policy_sha256,
        limits: ResourceLimits {
            max_archive_bytes,
            max_files,
            max_member_bytes,
            max_total_bytes,
            max_ratio: max_ratio_present.then_some(max_ratio_value),
            max_path_depth,
            max_metadata_bytes,
        },
    };
    if !max_ratio_present && max_ratio_value != 0 {
        return Err(ProtocolError::new(
            ProtocolErrorKind::InvalidSemanticState,
            FRAME_HEADER_BYTES + 172,
            "absent max ratio has a nonzero value",
        ));
    }
    validate_start(&request, received_capabilities)?;
    Ok(request)
}

/// Encodes a validated version 1 worker result.
pub fn encode_result(result: &WorkerResult) -> Result<Vec<u8>, ProtocolError> {
    validate_result(result)?;
    let payload_len = result_payload_len(result)?;
    let total_len = FRAME_HEADER_BYTES
        .checked_add(payload_len)
        .ok_or_else(|| overflow("result frame length overflowed"))?;
    if total_len > MAX_FRAME_BYTES {
        return Err(limit(0, "result frame exceeds the wire limit"));
    }
    let mut output = allocate_frame(total_len)?;
    encode_header(&mut output, FRAME_KIND_RESULT, payload_len)?;
    output.extend_from_slice(&result.operation_id);
    output.push(match result.status {
        WorkerStatus::Complete => 1,
        WorkerStatus::Rejected => 2,
        WorkerStatus::Failed => 3,
    });
    let root_flags =
        u8::from(result.layout_root.is_some()) | (u8::from(result.content_root.is_some()) << 1);
    output.push(root_flags);
    push_u16(&mut output, 0);
    push_u32(&mut output, result.manifest.len() as u32);
    push_u32(&mut output, result.findings.len() as u32);
    output.extend_from_slice(&result.interpretation_profile_sha256);
    output.extend_from_slice(&result.layout_root.unwrap_or([0; 32]));
    output.extend_from_slice(&result.content_root.unwrap_or([0; 32]));

    for entry in &result.manifest {
        push_u16(&mut output, entry.path.len() as u16);
        output.push(match entry.kind {
            ManifestKind::File => 1,
            ManifestKind::Directory => 2,
        });
        output.push(0);
        push_u64(&mut output, entry.size);
        output.extend_from_slice(&entry.sha256);
        output.extend_from_slice(entry.path.as_bytes());
    }
    for finding in &result.findings {
        push_u16(&mut output, finding.code.len() as u16);
        push_u16(&mut output, finding.detail.len() as u16);
        push_u16(
            &mut output,
            finding
                .member_path
                .as_ref()
                .map_or(NO_CAPABILITY_SLOT, |path| path.len() as u16),
        );
        output.push(match finding.severity {
            FindingSeverity::Warning => 1,
            FindingSeverity::Error => 2,
        });
        output.push(0);
        output.extend_from_slice(finding.code.as_bytes());
        output.extend_from_slice(finding.detail.as_bytes());
        if let Some(path) = &finding.member_path {
            output.extend_from_slice(path.as_bytes());
        }
    }
    debug_assert_eq!(output.len(), total_len);
    Ok(output)
}

/// Decodes a complete result frame for an expected operation.
///
/// `received_capabilities` must be zero because results cannot grant authority
/// back to the supervisor.
pub fn decode_result(
    input: &[u8],
    expected_operation_id: [u8; 16],
    received_capabilities: u16,
) -> Result<WorkerResult, ProtocolError> {
    if received_capabilities != 0 {
        return Err(ProtocolError::new(
            ProtocolErrorKind::CapabilityMismatch,
            0,
            "worker result must not carry capabilities",
        ));
    }
    let payload = decode_header(input, FRAME_KIND_RESULT)?;
    if payload.len() < RESULT_FIXED_PAYLOAD_BYTES {
        return Err(ProtocolError::new(
            ProtocolErrorKind::Truncated,
            FRAME_HEADER_BYTES,
            "result fixed payload is truncated",
        ));
    }
    let mut cursor = Cursor::new(payload, FRAME_HEADER_BYTES);
    let operation_id = cursor.array()?;
    if operation_id != expected_operation_id {
        return Err(cursor.error(
            ProtocolErrorKind::CorrelationMismatch,
            "worker result operation ID does not match",
        ));
    }
    let status = match cursor.u8()? {
        1 => WorkerStatus::Complete,
        2 => WorkerStatus::Rejected,
        3 => WorkerStatus::Failed,
        _ => return Err(cursor.error(ProtocolErrorKind::InvalidEnum, "unknown worker status")),
    };
    let root_flags = cursor.u8()?;
    if root_flags & !0b11 != 0 {
        return Err(cursor.error(
            ProtocolErrorKind::ReservedNonZero,
            "result root flags contain reserved bits",
        ));
    }
    require_zero(cursor.u16()?, &cursor, "result reserved field is nonzero")?;
    let member_count = cursor.u32()?;
    let finding_count = cursor.u32()?;
    if member_count > MAX_MANIFEST_MEMBERS {
        return Err(limit(
            cursor.absolute(),
            "manifest member count exceeds the limit",
        ));
    }
    if finding_count > MAX_FINDINGS {
        return Err(limit(cursor.absolute(), "finding count exceeds the limit"));
    }
    let interpretation_profile_sha256 = cursor.array()?;
    let layout_bytes: [u8; 32] = cursor.array()?;
    let content_bytes: [u8; 32] = cursor.array()?;
    let layout_root = decode_optional_digest(root_flags & 1 != 0, layout_bytes, &cursor)?;
    let content_root = decode_optional_digest(root_flags & 2 != 0, content_bytes, &cursor)?;

    let member_count_usize = member_count as usize;
    let minimum_member_bytes = member_count_usize
        .checked_mul(MANIFEST_ENTRY_FIXED_BYTES + 1)
        .ok_or_else(|| overflow("minimum manifest length overflowed"))?;
    if minimum_member_bytes > cursor.remaining() {
        return Err(cursor.error(
            ProtocolErrorKind::CountInconsistent,
            "manifest count cannot fit in the remaining payload",
        ));
    }
    let mut manifest: Vec<ManifestEntry> = Vec::new();
    manifest
        .try_reserve_exact(member_count_usize)
        .map_err(|_| {
            cursor.error(
                ProtocolErrorKind::AllocationFailed,
                "could not reserve the bounded manifest",
            )
        })?;
    for _ in 0..member_count {
        let path_len = cursor.u16()? as usize;
        if path_len == 0 || path_len > MAX_PATH_BYTES {
            return Err(limit(
                cursor.absolute(),
                "manifest path length is outside the limit",
            ));
        }
        let kind = match cursor.u8()? {
            1 => ManifestKind::File,
            2 => ManifestKind::Directory,
            _ => {
                return Err(cursor.error(
                    ProtocolErrorKind::InvalidEnum,
                    "unknown manifest member kind",
                ));
            }
        };
        require_zero(cursor.u8()?, &cursor, "manifest reserved byte is nonzero")?;
        let size = cursor.u64()?;
        let sha256 = cursor.array()?;
        let path = cursor.bounded_string(path_len, StringKind::Path)?;
        if let Some(previous) = manifest.last() {
            if previous.path.as_str() >= path.as_str() {
                return Err(cursor.error(
                    ProtocolErrorKind::NonCanonicalOrder,
                    "manifest paths are not strictly ordered",
                ));
            }
        }
        if kind == ManifestKind::Directory && (size != 0 || sha256 != [0; 32]) {
            return Err(cursor.error(
                ProtocolErrorKind::InvalidSemanticState,
                "directory manifest entry carries file content evidence",
            ));
        }
        manifest.push(ManifestEntry {
            path,
            kind,
            size,
            sha256,
        });
    }

    let finding_count_usize = finding_count as usize;
    let minimum_finding_bytes = finding_count_usize
        .checked_mul(FINDING_FIXED_BYTES + 1)
        .ok_or_else(|| overflow("minimum finding length overflowed"))?;
    if minimum_finding_bytes > cursor.remaining() {
        return Err(cursor.error(
            ProtocolErrorKind::CountInconsistent,
            "finding count cannot fit in the remaining payload",
        ));
    }
    let mut findings = Vec::new();
    findings
        .try_reserve_exact(finding_count_usize)
        .map_err(|_| {
            cursor.error(
                ProtocolErrorKind::AllocationFailed,
                "could not reserve the bounded findings",
            )
        })?;
    for _ in 0..finding_count {
        let code_len = cursor.u16()? as usize;
        let detail_len = cursor.u16()? as usize;
        let encoded_path_len = cursor.u16()?;
        if code_len == 0 || code_len > MAX_FINDING_CODE_BYTES {
            return Err(limit(
                cursor.absolute(),
                "finding code length is outside the limit",
            ));
        }
        if detail_len > MAX_FINDING_DETAIL_BYTES {
            return Err(limit(
                cursor.absolute(),
                "finding detail length exceeds the limit",
            ));
        }
        if encoded_path_len != NO_CAPABILITY_SLOT && encoded_path_len as usize > MAX_PATH_BYTES {
            return Err(limit(
                cursor.absolute(),
                "finding path length exceeds the limit",
            ));
        }
        let severity = match cursor.u8()? {
            1 => FindingSeverity::Warning,
            2 => FindingSeverity::Error,
            _ => {
                return Err(
                    cursor.error(ProtocolErrorKind::InvalidEnum, "unknown finding severity")
                );
            }
        };
        require_zero(cursor.u8()?, &cursor, "finding reserved byte is nonzero")?;
        let code = cursor.bounded_string(code_len, StringKind::FindingCode)?;
        let detail = cursor.bounded_string(detail_len, StringKind::Detail)?;
        let member_path = if encoded_path_len == NO_CAPABILITY_SLOT {
            None
        } else {
            Some(cursor.bounded_string(encoded_path_len as usize, StringKind::Path)?)
        };
        findings.push(ProtocolFinding {
            severity,
            code,
            detail,
            member_path,
        });
    }
    cursor.finish()?;
    let result = WorkerResult {
        operation_id,
        status,
        interpretation_profile_sha256,
        layout_root,
        content_root,
        manifest,
        findings,
    };
    validate_result(&result)?;
    Ok(result)
}

fn validate_start(request: &StartRequest, received_capabilities: u16) -> Result<(), ProtocolError> {
    if request.operation_id == [0; 16] {
        return Err(invalid_state("operation ID must be nonzero"));
    }
    if request.capability_count > MAX_CAPABILITIES
        || request.capability_count != received_capabilities
    {
        return Err(ProtocolError::new(
            ProtocolErrorKind::CapabilityMismatch,
            0,
            "declared and received capability counts do not match",
        ));
    }
    if request.source_capability >= request.capability_count {
        return Err(ProtocolError::new(
            ProtocolErrorKind::CapabilityMismatch,
            0,
            "source capability slot is unavailable",
        ));
    }
    match request.mode {
        ExecutionMode::Inspect => {
            if request.capability_count != 1 || request.stage_capability.is_some() {
                return Err(ProtocolError::new(
                    ProtocolErrorKind::CapabilityMismatch,
                    0,
                    "inspect mode requires only the source capability",
                ));
            }
        }
        ExecutionMode::Materialize => {
            let stage = request.stage_capability.ok_or_else(|| {
                ProtocolError::new(
                    ProtocolErrorKind::CapabilityMismatch,
                    0,
                    "materialize mode requires a stage capability",
                )
            })?;
            if request.capability_count != 2
                || stage >= request.capability_count
                || stage == request.source_capability
            {
                return Err(ProtocolError::new(
                    ProtocolErrorKind::CapabilityMismatch,
                    0,
                    "materialize capability slots are invalid",
                ));
            }
        }
    }
    if request.source_len > request.limits.max_archive_bytes {
        return Err(invalid_state(
            "source length exceeds the transmitted archive limit",
        ));
    }
    Ok(())
}

fn validate_result(result: &WorkerResult) -> Result<(), ProtocolError> {
    if result.operation_id == [0; 16] {
        return Err(invalid_state("operation ID must be nonzero"));
    }
    if result.manifest.len() > MAX_MANIFEST_MEMBERS as usize {
        return Err(limit(0, "manifest member count exceeds the limit"));
    }
    if result.findings.len() > MAX_FINDINGS as usize {
        return Err(limit(0, "finding count exceeds the limit"));
    }
    match result.status {
        WorkerStatus::Complete => {
            if result.layout_root.is_none() || result.content_root.is_none() {
                return Err(invalid_state(
                    "complete result requires both semantic roots",
                ));
            }
            if result
                .findings
                .iter()
                .any(|finding| finding.severity == FindingSeverity::Error)
            {
                return Err(invalid_state(
                    "complete result cannot carry an error finding",
                ));
            }
        }
        WorkerStatus::Rejected | WorkerStatus::Failed => {
            if !result.manifest.is_empty() || result.content_root.is_some() {
                return Err(invalid_state(
                    "non-complete result cannot carry a manifest or content root",
                ));
            }
            if !result
                .findings
                .iter()
                .any(|finding| finding.severity == FindingSeverity::Error)
            {
                return Err(invalid_state(
                    "non-complete result requires an error finding",
                ));
            }
        }
    }
    let mut previous: Option<&str> = None;
    for entry in &result.manifest {
        validate_string(&entry.path, StringKind::Path)?;
        if previous.is_some_and(|path| path >= entry.path.as_str()) {
            return Err(ProtocolError::new(
                ProtocolErrorKind::NonCanonicalOrder,
                0,
                "manifest paths are not strictly ordered",
            ));
        }
        if entry.kind == ManifestKind::Directory && (entry.size != 0 || entry.sha256 != [0; 32]) {
            return Err(invalid_state(
                "directory manifest entry carries file content evidence",
            ));
        }
        previous = Some(&entry.path);
    }
    for finding in &result.findings {
        validate_string(&finding.code, StringKind::FindingCode)?;
        validate_string(&finding.detail, StringKind::Detail)?;
        if let Some(path) = &finding.member_path {
            validate_string(path, StringKind::Path)?;
        }
    }
    Ok(())
}

fn result_payload_len(result: &WorkerResult) -> Result<usize, ProtocolError> {
    let mut len = RESULT_FIXED_PAYLOAD_BYTES;
    for entry in &result.manifest {
        len = len
            .checked_add(MANIFEST_ENTRY_FIXED_BYTES)
            .and_then(|value| value.checked_add(entry.path.len()))
            .ok_or_else(|| overflow("manifest encoding length overflowed"))?;
    }
    for finding in &result.findings {
        len = len
            .checked_add(FINDING_FIXED_BYTES)
            .and_then(|value| value.checked_add(finding.code.len()))
            .and_then(|value| value.checked_add(finding.detail.len()))
            .and_then(|value| {
                value.checked_add(finding.member_path.as_ref().map_or(0, String::len))
            })
            .ok_or_else(|| overflow("finding encoding length overflowed"))?;
    }
    Ok(len)
}

fn allocate_frame(total_len: usize) -> Result<Vec<u8>, ProtocolError> {
    if total_len > MAX_FRAME_BYTES {
        return Err(limit(0, "frame exceeds the wire limit"));
    }
    let mut output = Vec::new();
    output.try_reserve_exact(total_len).map_err(|_| {
        ProtocolError::new(
            ProtocolErrorKind::AllocationFailed,
            0,
            "could not reserve the bounded frame",
        )
    })?;
    Ok(output)
}

fn encode_header(output: &mut Vec<u8>, kind: u8, payload_len: usize) -> Result<(), ProtocolError> {
    let payload_len = u32::try_from(payload_len)
        .map_err(|_| overflow("payload length does not fit the wire field"))?;
    output.extend_from_slice(&FRAME_MAGIC);
    push_u16(output, PROTOCOL_VERSION);
    output.push(kind);
    output.push(0);
    push_u32(output, payload_len);
    Ok(())
}

fn decode_header(input: &[u8], expected_kind: u8) -> Result<&[u8], ProtocolError> {
    if input.len() > MAX_FRAME_BYTES {
        return Err(ProtocolError::new(
            ProtocolErrorKind::FrameTooLarge,
            0,
            "frame exceeds the wire limit",
        ));
    }
    if input.len() < FRAME_HEADER_BYTES {
        return Err(ProtocolError::new(
            ProtocolErrorKind::Truncated,
            input.len(),
            "frame header is truncated",
        ));
    }
    if input[..8] != FRAME_MAGIC {
        return Err(ProtocolError::new(
            ProtocolErrorKind::InvalidMagic,
            0,
            "frame magic does not match",
        ));
    }
    let version = u16::from_le_bytes([input[8], input[9]]);
    if version != PROTOCOL_VERSION {
        return Err(ProtocolError::new(
            ProtocolErrorKind::UnsupportedVersion,
            8,
            "protocol version is unsupported",
        ));
    }
    if input[10] != expected_kind {
        return Err(ProtocolError::new(
            ProtocolErrorKind::UnexpectedFrameKind,
            10,
            "frame kind does not match the decoder",
        ));
    }
    if input[11] != 0 {
        return Err(ProtocolError::new(
            ProtocolErrorKind::ReservedNonZero,
            11,
            "header reserved byte is nonzero",
        ));
    }
    let payload_len = u32::from_le_bytes([input[12], input[13], input[14], input[15]]) as usize;
    let expected_len = FRAME_HEADER_BYTES
        .checked_add(payload_len)
        .ok_or_else(|| overflow("frame length overflowed"))?;
    if expected_len > input.len() {
        return Err(ProtocolError::new(
            ProtocolErrorKind::Truncated,
            input.len(),
            "declared payload is truncated",
        ));
    }
    if expected_len < input.len() {
        return Err(ProtocolError::new(
            ProtocolErrorKind::TrailingBytes,
            expected_len,
            "bytes follow the declared payload",
        ));
    }
    Ok(&input[FRAME_HEADER_BYTES..])
}

#[derive(Clone, Copy)]
enum StringKind {
    Path,
    FindingCode,
    Detail,
}

fn validate_string(value: &str, kind: StringKind) -> Result<(), ProtocolError> {
    let valid = match kind {
        StringKind::Path => {
            !value.is_empty()
                && value.len() <= MAX_PATH_BYTES
                && value.is_ascii()
                && !value.starts_with('/')
                && !value.ends_with('/')
                && !value.contains('\\')
                && value.split('/').all(valid_path_component)
        }
        StringKind::FindingCode => {
            !value.is_empty()
                && value.len() <= MAX_FINDING_CODE_BYTES
                && value.as_bytes()[0].is_ascii_lowercase()
                && value.bytes().all(|byte| {
                    byte.is_ascii_lowercase()
                        || byte.is_ascii_digit()
                        || byte == b'.'
                        || byte == b'_'
                })
        }
        StringKind::Detail => {
            value.len() <= MAX_FINDING_DETAIL_BYTES && !value.chars().any(char::is_control)
        }
    };
    if valid {
        Ok(())
    } else {
        Err(ProtocolError::new(
            ProtocolErrorKind::InvalidString,
            0,
            match kind {
                StringKind::Path => "path is not a bounded canonical relative path",
                StringKind::FindingCode => "finding code is not in the wire language",
                StringKind::Detail => "finding detail contains a control or exceeds its limit",
            },
        ))
    }
}

fn valid_path_component(component: &str) -> bool {
    if component.is_empty()
        || component == "."
        || component == ".."
        || component.contains(':')
        || component.ends_with('.')
        || component.ends_with(' ')
        || component
            .bytes()
            .any(|byte| byte.is_ascii_control() || b"<>\"|?*".contains(&byte))
    {
        return false;
    }
    let stem = component.split('.').next().unwrap_or(component);
    ![
        "CON", "PRN", "AUX", "NUL", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8",
        "COM9", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9",
    ]
    .iter()
    .any(|reserved| stem.eq_ignore_ascii_case(reserved))
}

fn decode_optional_digest(
    present: bool,
    bytes: [u8; 32],
    cursor: &Cursor<'_>,
) -> Result<Option<[u8; 32]>, ProtocolError> {
    if present {
        Ok(Some(bytes))
    } else if bytes == [0; 32] {
        Ok(None)
    } else {
        Err(cursor.error(
            ProtocolErrorKind::InvalidSemanticState,
            "absent root has nonzero wire bytes",
        ))
    }
}

fn decode_bool(
    value: u8,
    cursor: &Cursor<'_>,
    detail: &'static str,
) -> Result<bool, ProtocolError> {
    match value {
        0 => Ok(false),
        1 => Ok(true),
        _ => Err(cursor.error(ProtocolErrorKind::InvalidEnum, detail)),
    }
}

fn require_zero<T>(value: T, cursor: &Cursor<'_>, detail: &'static str) -> Result<(), ProtocolError>
where
    T: PartialEq + Default,
{
    if value == T::default() {
        Ok(())
    } else {
        Err(cursor.error(ProtocolErrorKind::ReservedNonZero, detail))
    }
}

fn push_u16(output: &mut Vec<u8>, value: u16) {
    output.extend_from_slice(&value.to_le_bytes());
}

fn push_u32(output: &mut Vec<u8>, value: u32) {
    output.extend_from_slice(&value.to_le_bytes());
}

fn push_u64(output: &mut Vec<u8>, value: u64) {
    output.extend_from_slice(&value.to_le_bytes());
}

fn limit(offset: usize, detail: &'static str) -> ProtocolError {
    ProtocolError::new(ProtocolErrorKind::LimitExceeded, offset, detail)
}

fn invalid_state(detail: &'static str) -> ProtocolError {
    ProtocolError::new(ProtocolErrorKind::InvalidSemanticState, 0, detail)
}

fn overflow(detail: &'static str) -> ProtocolError {
    ProtocolError::new(ProtocolErrorKind::IntegerOverflow, 0, detail)
}

struct Cursor<'a> {
    input: &'a [u8],
    position: usize,
    base: usize,
}

impl<'a> Cursor<'a> {
    fn new(input: &'a [u8], base: usize) -> Self {
        Self {
            input,
            position: 0,
            base,
        }
    }

    fn absolute(&self) -> usize {
        self.base.saturating_add(self.position)
    }

    fn remaining(&self) -> usize {
        self.input.len().saturating_sub(self.position)
    }

    fn error(&self, kind: ProtocolErrorKind, detail: &'static str) -> ProtocolError {
        ProtocolError::new(kind, self.absolute(), detail)
    }

    fn bytes(&mut self, len: usize) -> Result<&'a [u8], ProtocolError> {
        let end = self
            .position
            .checked_add(len)
            .ok_or_else(|| overflow("cursor length overflowed"))?;
        let bytes = self.input.get(self.position..end).ok_or_else(|| {
            self.error(
                ProtocolErrorKind::Truncated,
                "field extends past the declared payload",
            )
        })?;
        self.position = end;
        Ok(bytes)
    }

    fn array<const N: usize>(&mut self) -> Result<[u8; N], ProtocolError> {
        let mut output = [0; N];
        output.copy_from_slice(self.bytes(N)?);
        Ok(output)
    }

    fn u8(&mut self) -> Result<u8, ProtocolError> {
        Ok(self.bytes(1)?[0])
    }

    fn u16(&mut self) -> Result<u16, ProtocolError> {
        Ok(u16::from_le_bytes(self.array()?))
    }

    fn u32(&mut self) -> Result<u32, ProtocolError> {
        Ok(u32::from_le_bytes(self.array()?))
    }

    fn u64(&mut self) -> Result<u64, ProtocolError> {
        Ok(u64::from_le_bytes(self.array()?))
    }

    fn zeroes(&mut self, len: usize, detail: &'static str) -> Result<(), ProtocolError> {
        if self.bytes(len)?.iter().all(|byte| *byte == 0) {
            Ok(())
        } else {
            Err(self.error(ProtocolErrorKind::ReservedNonZero, detail))
        }
    }

    fn bounded_string(&mut self, len: usize, kind: StringKind) -> Result<String, ProtocolError> {
        let offset = self.absolute();
        let bytes = self.bytes(len)?;
        let borrowed = std::str::from_utf8(bytes).map_err(|_| {
            ProtocolError::new(
                ProtocolErrorKind::InvalidUtf8,
                offset,
                "wire string is not UTF-8",
            )
        })?;
        validate_string(borrowed, kind).map_err(|mut error| {
            error.offset = offset;
            error
        })?;
        let mut owned = String::new();
        owned.try_reserve_exact(len).map_err(|_| {
            ProtocolError::new(
                ProtocolErrorKind::AllocationFailed,
                offset,
                "could not reserve a bounded wire string",
            )
        })?;
        owned.push_str(borrowed);
        Ok(owned)
    }

    fn finish(&self) -> Result<(), ProtocolError> {
        if self.position == self.input.len() {
            Ok(())
        } else {
            Err(self.error(
                ProtocolErrorKind::TrailingBytes,
                "unconsumed bytes remain inside the payload",
            ))
        }
    }
}
